DATA_SOURCE = 'data/AMAZON_FASHION.parquet'
TRAIN_DATA_SOURCE = 'data/AMAZON_FASHION_TRAIN.parquet'
LENGTH = 5000
VOCAB_SIZE = 1000
BATCH_SIZE = 64
ARTIFACT_STORE = 'artifacts'
EPOCHS = 10
STEPS_PER_EPOCH = 100