name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: DockerHub Login
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - name: Build the Docker image
      run: docker build -t cicd-sentiment-analyzer .
    - name: Push to Dockerhub
      run: docker push skhapijulhossen/cicd-pipeline:latest
    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag sentimentanalyzer:$(date +%s)
